name: Hello workflow

on:
   push:
      branches: [main]

jobs:
   greet:
   #Runner act as server to run the Job
      runs-on: ubuntu-latest
      steps:
         - name: hello to all users
           run: echo "Hello  Mitro"

         - name: hello to username
           run: echo "Hello $USER"
   deatils:
      runs-on: ubuntu-latest
      steps:
         - name: show what is the version of apps
           run: docker --version && python --version
